name: Release new version

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      # NOTE: We need this because otherwise the build fails with:
      #
      #    bwrap: setting up uid map: Permission denied
      - name: Disable AppArmor unprivileged userns restriction
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Build the project
        run: nix build '.#foreign'

      - name: Prepare binaries for release
        run: |
          mkdir out
          cp result/bin/papertoy out/papertoy-linux-x86_64

      - name: Create new version as draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: out/*
          fail_on_unmatched_files: true
          generate_release_notes: true
